"""create wallet tables

Revision ID: f2b647a1f5a6
Revises:
Create Date: 2026-08-27 12:34:49.802266
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f2b647a1f5a6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("balance", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("balance >= 0", name="ck_wallets_balance_non_negative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wallet_operations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("operation_type", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("balance_after", sa.BigInteger(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "operation_type IN ('DEPOSIT', 'WITHDRAW')",
            name="ck_wallet_operations_type",
        ),
        sa.CheckConstraint("amount > 0", name="ck_wallet_operations_amount_positive"),
        sa.CheckConstraint(
            "balance_after >= 0", name="ck_wallet_operations_balance_non_negative"
        ),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "wallet_id",
            "idempotency_key",
            name="uq_wallet_operations_wallet_idempotency_key",
        ),
    )
    op.create_index(
        op.f("ix_wallet_operations_wallet_id"),
        "wallet_operations",
        ["wallet_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wallet_operations_wallet_id"), table_name="wallet_operations"
    )
    op.drop_table("wallet_operations")
    op.drop_table("wallets")
    # ### end Alembic commands ###
